# Generated by Django 4.0 on 2022-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='band',
            field=models.CharField(max_length=200, verbose_name='バンド名'),
        ),
    ]
