# Generated by Django 4.0 on 2022-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_schedule_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='band',
            field=models.CharField(max_length=200, verbose_name='予約バンド'),
        ),
    ]
