# Generated by Django 4.0 on 2022-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='予約日(mm/dd)'),
        ),
    ]
